spring:
 application:
  name: another-service
  
server:
  port:
    8052
        
    
eureka:
  client:
  #to regsiter this service Service Discovery
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
